### ISSUE TITLE
Play/pause not working over bluetooth 

### ISSUE THREAD

**Issue by DBendit** [Mach5/supersonic#12]
I still haven't figured out if it's my car radio or the app, but my play/pause button doesn't do anything. I'll look into this later.

**Comment by porkcharsui** [comment]
I noticed while testing the latest code on CM 7.1 on my Evo4g that I could occasionally cause supersonic to loose audio focus. Listen app would start playing an old podcast but I could next track back to supersonic. In addition, Navigation will not return focus after some directions are read. A minute later a new direction came and returned focus so volume levels were restored.

**Comment by DBendit** [comment]
Would Listen start playing only on hitting some control (play, next, etc.), or just seemingly at random?

As for Navigation, not sure what that's about. I hate to say that it works fine for me, but that's the whole reason I switched it over to using audio focus, and it seems to be working great on my end.

Mind sending me a log of it happening if you see it in the future?

**Comment by porkcharsui** [comment]
Listen would require a button press to take focus.

The audio focus changes are definitely working better than stock Subsonic.
If I encounter anything again like I described I will post logs using
LogCat.

-Derek
On Feb 19, 2012 5:55 PM, "David Bendit" <
reply@reply.github.com>
wrote:

**Comment by timoreimann** [comment]
Is this issue possibly fixed by pull request #43?

**Comment by DBendit** [comment]
I haven't tested it, but I think it will be. I can load it on my phone and test it out tonight.

**Comment by timoreimann** [comment]
Sounds good. Let me know if it works or close this issue directly in case it does.

Thanks!

**Comment by DBendit** [comment]
I had to make some other changes that I have yet to test, but the overall issue (play/pause not doing anything) seems to be resolved. Closing the issue.
