### ISSUE TITLE
Notification doesn't go away on stop over bluetooth 

### ISSUE THREAD

**Issue by DBendit** [Mach5/supersonic#13]
Hitting the stop button on my bluetooth radio stops properly (music stops, position resets), but the notification doesn't disappear.

**Comment by porkcharsui** [comment]
Just wanted to confirm you're talking about the notification area showing the song/album being played even where the player is not playing (opening Supersonic shows the play button in the not playing state). I believe I observed that today hours after I exited my car but I haven't pinpointed the conditions that triggered it.

**Comment by DBendit** [comment]
I've only been able to reproduce it when sending a STOP message over bluetooth. Simply pausing dismisses the notification just fine.

I'll fix it someday. Real life is doing a darn good job of keeping me away from this :)

**Comment by DBendit** [comment]
It's been a decade and I haven't fixed this. Closing.
