### ISSUE TITLE
re-label the Debian package

### ISSUE THREAD

**Issue by timoreimann** [Mach5/supersonic#18]
The Debian package should be re-labelled from Subsonic to Supersonic.

Quick question before I get to this: What official contact (name, email address) shall we use for certain Debian package fields (e.g., maintainer)?

I'd be fine with something generic (which we may need to create in the first place). Then again, Derek, you founded this project so I'd be fine with having any contact you choose to use (for instance, your own).

Any thoughts?

**Comment by porkcharsui** [comment]
Sounds good! 

I would prefer to use the Mach5 _organization_ to be the project's contact to better reflect the collaborative nature of this effort. Not sure about how to handle email without having a custom domain as of today.

Commit 1beb8affd0 shows me renaming the main project branding in light of the Mach5 transition.

**Comment by timoreimann** [comment]
Alright, I'll leave out any email addresses for the moment and try to make the Debian package build nicely.

**Comment by timoreimann** [comment]
Fixed in commit ca5d4e7b. For me moment, I marked myself as maintainer since I'm quite familiar with Debian and would like to continue being responsible even after this patch.

**Comment by porkcharsui** [comment]
Sounds good. I posted a comment on one line of ca5d4e7b regarding variable names.

**Comment by timoreimann** [comment]
Replied to your comment and fixed the variable naming bug you spotted. Thanks!
