### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by porkcharsui** [Mach5/supersonic#19]
The project needs the Wiki to be updated to include how to setup your development workstation to build Supersonic. Coding conventions might be included as well.

**Comment by timoreimann** [comment]
There's a [Developer section](http://sourceforge.net/apps/mediawiki/subsonic/index.php?title=Developer) on the Subsonic wiki including a page on [how to build Subsonic](http://sourceforge.net/apps/mediawiki/subsonic/index.php?title=Installing_Starting_And_Stopping_Subsonic#Building_from_source). It's not really fleshed out but may serve as a starter for ideas.

**Comment by porkcharsui** [comment]
Awesome just the starting point I was looking for!

**Comment by timoreimann** [comment]
The wiki now contains some level of developer documentation. If anything more particular should be added please file a separate issue (or update the wiki right away).
