### ISSUE TITLE
set up a forum/mailing list

### ISSUE THREAD

**Issue by timoreimann** [Mach5/supersonic#21]
There should be a way for people to communicate within the project. This involves both user and development discussions.

I'd propose to set up two Google groups, e.g., supersonic-users and supersonic-dev. While we may not need the user/dev distinction as of now I think it's good to separate things right away and save the trouble later.

Feedback?

**Comment by timoreimann** [comment]
Naturally, the groups would be referenced on the wiki as well.

**Comment by porkcharsui** [comment]
Great idea Timo! I setup both groups per your suggestion and will add links from the wiki.

[Supersonic Developers](https://groups.google.com/forum/#!forum/supersonic-dev)
[Supersonic Users](https://groups.google.com/forum/#!forum/supersonic-users)

**Comment by timoreimann** [comment]
Fantastic, thanks!

If I am not mistaken, membership to the users group requires approval while posting to the developers group is possible right away. Just wondering if this is the intended way people should be supposed to gain access to each group?

**Comment by porkcharsui** [comment]
I just modified the user permissions so anyone should be able to post and
join as members. I'll keep monitoring to make sure everything is working.

On Sun, Mar 4, 2012 at 4:23 PM, Timo Reimann <
reply@reply.github.com
