### ISSUE TITLE
rebrand remaining Maven projects

### ISSUE THREAD

**Issue by timoreimann** [Mach5/supersonic#22]
A couple of Maven projects still need some rebranding, e.g., _subsonic-installer-windows_ and _subsonic-installer-mac_. This isn't just for the looks but because these projects won't build at the moment due to mismatching parent definitions.

**Comment by porkcharsui** [comment]
Good call this definitely feels like a high priority task. I'll be working towards the automated WAR upload -- #11

**Comment by timoreimann** [comment]
subsonic-installer-mac has been rebranded along commit 3b06baa.

**Comment by timoreimann** [comment]
Looks like all projects have been rebranded. Closing issue.
