### ISSUE TITLE
CSS & JS Compression

### ISSUE THREAD

**Issue by nicolasberens** [Mach5/supersonic#33]
Integrate the YUI Compressor into Maven
http://alchim.sourceforge.net/yuicompressor-maven-plugin/

I'm going to do that, and this ticket is just a placeholder so im rembered to this and nobody else does it ;-)

**Comment by porkcharsui** [comment]
This is definitely a quick feature change that will have good benefit for end users of the WebUI. I personally have implemented @alexo/wro4j and found it to be a quick drop with lots of extra cool features (CSS pre processors, JS lint etc)

http://code.google.com/p/wro4j/

**Comment by nicolasberens** [comment]
at the moment im using the YUI Compressor, simply because you get it running with 10 lines of code in the pom.xml 

wait a minute, i create a pull request

**Comment by nicolasberens** [comment]
and there it is, the pull request #35
https://github.com/Mach5/supersonic/pull/35

**Comment by nicolasberens** [comment]
after messing up my git branch, i think it would be easier when someone takes the pom.xml from my repo and inserts it into the supersonic repo,
https://github.com/rtznprmpftl/supersonic/blob/master/pom.xml

**Comment by timoreimann** [comment]
I'm on it.

**Comment by timoreimann** [comment]
@rtznprmpftl, would you mind taking a quick look at the newly created _yui_compressor_ branch under

https://github.com/Mach5/supersonic/tree/yui_compressor

and let me know I did things right?

It covers two commits: 1a53ab8 which represents your changes (namely adding YUI compressor); and fc3bfde which is a minor on-top change removing the version specification from the plugin configuration to get rid of a Maven warning.

Given your acknowledgement I will merge the branch into master.

**Comment by nicolasberens** [comment]
seems ok

**Comment by timoreimann** [comment]
Thanks a lot -- and sorry again for any confusion I've created.

Approved, merged, and closed.
