### ISSUE TITLE
Ignored Debian default file variables

### ISSUE THREAD

**Issue by Booloki** [Mach5/supersonic#39]
subsonic-installer-debian/src/etc/default/supersonic file has wrong variables. Please replace Subsonic_ARGS by SUBSONIC_ARGS and Subsonic_USER by SUBSONIC_USER (upstream subsonic file is OK) in order to be taken in account by Debian initscript.
Thanks

**Comment by porkcharsui** [comment]
Thanks for the feedback!

**Comment by Booloki** [comment]
Thanks
