### ISSUE TITLE
No INSTALL file

### ISSUE THREAD

**Issue by Rovanion** [Mach5/supersonic#40]
The project needs clear instructions on how to build and install from source. These instructions should be added to a file called INSTALL in the project root as is common.

I'm currently unable to figure out how to build from source, if someone could fill me in I will create an INSTALL file and commit it once I'm done.

**Comment by porkcharsui** [comment]
You'll need Maven and a JDK installed on your machine to get started on the main server component. Enter the directory from a command line that can access git...

### Simple

`mvn clean install` - creates a WAR file inside `subsonic-main/target/`

### Installers

Requires EXE4j and NSIS for Windows (see `subsonic-tools`). Be sure to install these into `c:\program files\` when you are using 64 bit Windows.

`mvn clean -P full
mvn install -P full`

### Packages

`cd subsonic-assembly
mvn assembly:assembly`

**Comment by timoreimann** [comment]
Fixed in commit 311895ef.
