### ISSUE TITLE
Wikipedia entry

### ISSUE THREAD

**Issue by porkcharsui** [Mach5/supersonic#45]
http://en.wikipedia.org/wiki/Subsonic_(media_server)

We should note our Subsonic fork and state the fork's goal is to be an API superset with no donate/licensing requirements.

**Comment by timoreimann** [comment]
Great idea! Showing some presence in Wikipedia should definitely prove helpful.

Moreover, I'd be willing to take a stab at creating an article for the German Wikipedia. A German Subsonic page is yet missing, however, and getting things into the German edition is said to be much harder overall.

Derek, if it's OK then I'll wait for your initiative and translate the English version accordingly.

**Comment by porkcharsui** [comment]
:) A German entry would be perfect! I just setup my account at Wikipedia so I'll write up a "fork" section this weekend to add to the entry. I will post here when I'm completed.

**Comment by porkcharsui** [comment]
Text has been added as of this entry: http://en.wikipedia.org/w/index.php?title=Subsonic_(media_server)&oldid=486212897

**Comment by timoreimann** [comment]
Looks good to me for a starter. Shall we close this issue then?
