### ISSUE TITLE
Unable to compile for Fedora 16

### ISSUE THREAD

**Issue by croax** [Mach5/supersonic#48]
lintian is not supplied for Fedora 16, why does Supersonic have to build the dpkg for a non-dpkg oriented system ?

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Supersonic ........................................ SUCCESS [1.732s]
[INFO] Supersonic Main ................................... SUCCESS [40.654s]
[INFO] Supersonic Booter ................................. SUCCESS [10.609s]
[INFO] Supersonic Installer for Windows .................. SUCCESS [0.034s]
[INFO] Supersonic Installer for Mac ...................... SUCCESS [0.019s]
[INFO] Supersonic Installer for Debian ................... FAILURE [3.995s]
[INFO] Supersonic Installer for RPM ...................... SKIPPED
[INFO] Supersonic Assembly ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.609s
[INFO] Finished at: Fri Apr 13 17:22:36 GMT 2012
[INFO] Final Memory: 50M/568M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (dpkg) on project supersonic-installer-debian: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "lintian" (in directory "/var/supersonic/subsonic-installer-debian"): java.io.IOException: error=2, No such file or directory -> [Help 1]

root@cyber supersonic]# pwd
/var/supersonic
[root@cyber supersonic]# ls -la
total 96
drwxr-xr-x  16 root root  4096 Apr 13 15:07 .
drwxr-xr-x. 34 root root  4096 Apr 13 16:32 ..
drwxr-xr-x   8 root root  4096 Apr 13 15:06 .git
-rw-r--r--   1 root root    52 Apr 13 15:06 .gitignore
-rw-r--r--   1 root root  2191 Apr 13 15:06 INSTALL
-rw-r--r--   1 root root 11808 Apr 13 15:06 pom.xml
-rw-r--r--   1 root root   373 Apr 13 15:06 .project
-rw-r--r--   1 root root   924 Apr 13 15:06 README.md
drwxr-xr-x   7 root root  4096 Apr 13 15:06 repo
drwxr-xr-x   7 root root  4096 Apr 13 15:06 subsonic-android
drwxr-xr-x   3 root root  4096 Apr 13 15:06 subsonic-assembly
drwxr-xr-x   4 root root  4096 Apr 13 17:22 subsonic-booter
drwxr-xr-x   3 root root  4096 Apr 13 15:06 subsonic-graphics
drwxr-xr-x   4 root root  4096 Apr 13 17:22 subsonic-installer-debian
drwxr-xr-x   3 root root  4096 Apr 13 15:06 subsonic-installer-mac
drwxr-xr-x   3 root root  4096 Apr 13 15:06 subsonic-installer-rpm
drwxr-xr-x   3 root root  4096 Apr 13 15:06 subsonic-installer-windows
drwxr-xr-x   4 root root  4096 Apr 13 17:21 subsonic-main
drwxr-xr-x   5 root root  4096 Apr 13 15:06 subsonic-tools
drwxr-xr-x   5 root root  4096 Apr 13 15:06 subsonic-transcode
drwxr-xr-x   3 root root  4096 Apr 13 15:06 supersonic-graphics
-rw-r--r--   1 root root   185 Apr 13 15:06 .travis.yml

**Comment by Rovanion** [comment]
The issue seems to be that you are trying to build for Debian and since dpkg doesn't exist in fedora the process errors out:

run (dpkg) on project supersonic-installer-debian

What command did you run in order to compile Subsonic?

**Comment by porkcharsui** [comment]
There might be an issue with the build scripts but please look at the INSTALL doc for more info in the meantime: 

https://github.com/Mach5/supersonic/blob/master/INSTALL

**Comment by timoreimann** [comment]
I'll close this issue because feedback from the OP has been outstanding for quite some time.

If the problem _is_ still persisting feel free to re-open.
