### ISSUE TITLE
Building outside of the git tree

### ISSUE THREAD

**Issue by sciurius** [Mach5/supersonic#62]
I want to build supersonic outside of the git tree, but currently this fails in an early stage:

[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.0:create (default) on project supersonic-main: Cannot get the revision information from the scm repository :

Apparently some plugin needs scm commands to get build information.
Can this be worked around?

**Comment by timoreimann** [comment]
I'd strongly advise against ignoring Git but if you must: Removing the _buildnumber-maven-plugin_ plugin section from **subsonic-main/pom.xml** should do the trick.

For future questions regarding building Supersonic please use the [developer's mailing list](https://groups.google.com/forum/#!forum/supersonic-dev) (and the [user's list](https://groups.google.com/forum/#!forum/supersonic-users) for user-related issues) unless it's really a bug.
