### ISSUE TITLE
Replaced subsonic with supersonic, music does not play.

### ISSUE THREAD

**Issue by chimpy** [Mach5/supersonic#69]
Hi guys,

Thanks for Supersonic! Though I'm slightly confused. Video is working fine, but I simply cannot get music to be added to the "now playing" playlist, or play at all.

Thoughts? Let me know if there's something I can provide (like a log of some sort) that I can help.

**Comment by timoreimann** [comment]
The issue tracker is supposed to be used for bug reports and feature requests only. For regular user questions, please switch to the [Supersonic Users mailing list](https://groups.google.com/forum/#!forum/supersonic-users).

I'll close the issue for now. To continue on your problem as quickly as possible, please describe **in a mailing list post** in more detail what you tried to achieve, what you expected to happen, and what the actual outcome was.
