### ISSUE TITLE
National characters i text-files makes the whole file Chinese!! (Windows)

### ISSUE THREAD

**Issue by AGjan** [Mach5/supersonic#76]
If we save a text file in the local directory, which contains Danish national characters, the file content is shown with Chinese characters (only) in GitHub's change documentation (Windows 7, 64bit). After Commit and Sync it is OK.

**Comment by timoreimann** [comment]
I'm not sure if I understand you correctly. Is this issue related to Supersonic per se or rather a Github matter?

**Comment by AGjan** [comment]
Hello Timo,

It’s a Github problem – I am sorry about the wrong category.
/Jan.

Fra: Timo Reimann [mailto:notifications@github.com]
Sendt: 2. oktober 2012 22:22
Til: Mach5/supersonic
Cc: Jan Ahlberg
Emne: Re: [supersonic] National characters i text-files makes the whole file Chinese!! (Windows) (#76)

I'm not sure if I understand you correctly. Is this issue related to Supersonic per se or rather a Github matter?

**Comment by timoreimann** [comment]
In that case, I suppose there's nothing we (as Supersonic community) can do to help with this issue. Maybe you want to get in touch with the Github folks directly and ask for support .

I'll close the issue for now if that's fine with you.
