### ISSUE TITLE
Error in file subsonic-main/src/main/java/net/sourceforge/subsonic/service/PodcastService.java

### ISSUE THREAD

**Issue by joswart** [Mach5/supersonic#79]
There is a '+' missing on line 223 of the file subsonic-main/src/main/java/net/sourceforge/subsonic/service/PodcastService.java

Original line:
                        LOG.info("Deleted Podcast episode '" + episode.getTitle() + "' because:" e.getMessage());

Should be:
                        LOG.info("Deleted Podcast episode '" + episode.getTitle() + "' because:" + e.getMessage());

**Comment by timoreimann** [comment]
I'm glad you pointed this out. We should have been notified about a failing build by Travis CI last time but for some reason it didn't happen.

By the way, if you like to make things a bit easier for us and yourself consider doing a pull request on your next bugfix. It's what makes Github a great collaboration platform and simplifies patching in third-party code, especially for non-trivial changes.

Thanks!

**Comment by joswart** [comment]
I will try that next time. Completely new to git and java development.

**Comment by timoreimann** [comment]
No worries -- git is a beast for newcomers, Github makes things just slightly easier. :)

Thanks again for contributing!
