### ISSUE TITLE
INSTALL should mention lintian for Debian based distros

### ISSUE THREAD

**Issue by joswart** [Mach5/supersonic#80]
The INSTALL should be updated with lintian for Debian based distros. Something like this would be helpful:
# Linux

First install the packages needed to build Supersonic. It depends on Java and
the Maven build environment:

Debian/Ubuntu/Mint
sudo apt-get install maven2 openjdk-6-jdk lintian

In this case lintian is added to the apt-get line.

**Comment by timoreimann** [comment]
Done!
